version: '2.1'

services:
  executor:
    privileged: true
    environment:
      - http_proxy
      - https_proxy
      - no_proxy=${no_proxy},gerrit,scheduler
      - ZUUL_MYSQL_PASSWORD=secret
    image: quay.io/zuul-ci/zuul-executor
    volumes:
      - "${ZUUL_TUTORIAL_CONFIG:-./etc_zuul/}:/etc/zuul/:z"
      - "./playbooks/:/var/playbooks/:z"
      - "sshkey:/var/ssh:z"
      - "logs:/srv/static/logs:z"
      - "certs:/var/certs:z"
      - "lib-zuul-executor:/var/lib/zuul:z"
    command: "sh -c '/var/playbooks/wait-to-start-certs.sh && exec zuul-executor -d -f'"
    networks:
      - zuul

volumes:
  sshkey:
  nodessh:
  logs:
  certs:
  lib-zuul-scheduler:
  lib-zuul-web:
  lib-zuul-executor:
  zk-data:
  zk-datalog:
  lib-mysql:
  gerrit-etc:
  gerrit-db:
  gerrit-git:
  gerrit-index:
  gerrit-cache:

networks:
  zuul:
