version: '2.1'

services:
  builder:
    image: quay.io/zuul-ci/nodepool-builder
    volumes:
      - "./playbooks/:/var/playbooks/:z"
      - "/etc/nodepool/:/etc/nodepool/:z"
      - "/etc/openstack/:/etc/openstack/:z"
      - "/etc/nodepool/elements/:/etc/nodepool/elements/:z"
      - "/etc/nodepool/dib/:/etc/nodepool/dib/:z"
      - "/etc/nodepool/dib_log/:/etc/nodepool/dib_log/:z"
      - "/etc/nodepool/dib_tmp/:/opt/dib_tmp/:z"
      - "certs:/var/certs:z"
    command: "sh -c '/var/playbooks/wait-to-start-certs.sh && exec nodepool-builder -f'"
    networks:
      - zuul
    privileged: true
    cap_add:
      - CAP_MKNOD
      - CAP_AUDIT_WRITE
      - CAP_SYS_ADMIN

volumes:
  certs:

networks:
  zuul:
