version: '2.1'

services:
  launcher:
    image: quay.io/zuul-ci/nodepool-launcher
    volumes:
      - "./playbooks/:/var/playbooks/:z"
      - "./etc_nodepool/:/etc/nodepool/:z"
      - "/etc/openstack/:/etc/openstack/:z"
      - "certs:/var/certs:z"
    ports:
      - "8005:8005"
    command: "sh -c '/var/playbooks/wait-to-start-certs.sh && exec nodepool-launcher -f'"
    networks:
      - zuul

volumes:
  certs:

networks:
  zuul:
