- hosts: all
  roles:
    - role: fetch-output
      zuul_output_dir: "{{ ansible_user_dir }}"
    - merge-output-to-logs

- hosts: localhost
  roles:
    - generate-zuul-manifest
    - role: upload-logs
      zuul_log_url: "http://10.228.225.12:8000"
